development:
  adapter: postgresql
  encoding: utf8
  database: development
  pool: 5
  username: root
  password: admin
  port: 5433
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: test
  pool: 5
  username: root
  password: admin
  port: 5433
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV.fetch("DB_NAME") { '' } %>
  pool: <%= ENV.fetch("DB_POOL") { '' } %>
  username: <%= ENV.fetch("DB_USER") { '' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { '' } %>
  port: <%= ENV.fetch("DB_PORT") { '' } %>